### PR TITLE
Two-in-one: fixed dataset templating and disabling of timeline vis

### LINKED ISSUE #2262: Map visualization is enabled when there is no location data.
**General description:** Map visualization is enabled when there is no location data. 

**live/dev/localhost:** live
**iSENSE Version:** v7.3.0
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 45.0.2454.101

**Steps to Reproduce:** 

393

### LINKED ISSUE #2295: Timeline enabled when there is no time data
**General description:** Timeline enabled when there is no time data

**live/dev/localhost:** live
**iSENSE Version:** v7.4.1
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** X11
**Browser/Version:** Chrome 46.0.2490.80

**Steps to Reproduce:** 

10

### PR DESCRIPTION
**Pull request by pat-son**
Since [this pull request](https://github.com/isenseDev/rSENSE/pull/2289) was failing due to a bug that [this other request](https://github.com/isenseDev/rSENSE/pull/2346) fixes, I merged them together. Also fixed another failing test. Fixes #2295 and #2271.

Also fixes #2262.

### CODE REVIEW

File: test/integration/delete_then_feature_mo_test.rb [hunk 1]
```diff
@@ -60,6 +60,7 @@ class DeleteThenFeatureMoTest < IntegrationTest
     within_window open_new_window do
       visit url
       accept_confirm do
+        screenshot_and_open_image
```
Comment (bdonald25) [inline test/integration/delete_then_feature_mo_test.rb]: remove

File: .rubocop.yml [hunk 2]
```diff
@@ -82,7 +82,7 @@ CollectionMethods:
 
 # Offence count: 23
 CyclomaticComplexity:
-  Max: 31
+  Max: 40
```
Comment (bdonald25) [inline .rubocop.yml]: No

Comment (pat-son) [inline .rubocop.yml]: I was told to change it (a while ago, this is an old change). If I don't, then visualizations_controller.rb doesn't pass rubocop. For this file to pass rubocop with a cyclomatic complexity of 31, the displayVis function would have to completely rewritten/split up into several functions.
